# Generated by Django 5.0.7 on 2024-07-22 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constants', '0003_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ac_month', models.DateField(blank=True, null=True)),
                ('b01_tufe', models.FloatField(blank=True, null=True)),
                ('b02_mineral', models.FloatField(blank=True, null=True)),
                ('b03_main_metal', models.FloatField(blank=True, null=True)),
                ('b04_other_metal', models.FloatField(blank=True, null=True)),
                ('b05_petrol', models.FloatField(blank=True, null=True)),
                ('b06_wood', models.FloatField(blank=True, null=True)),
                ('b07_electricity', models.FloatField(blank=True, null=True)),
                ('b08_computer', models.FloatField(blank=True, null=True)),
                ('b09_ufe', models.FloatField(blank=True, null=True)),
                ('b10_machinety', models.FloatField(blank=True, null=True)),
                ('r_usd_try', models.FloatField(blank=True, null=True)),
                ('r_eur_try', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_indexes_base',
                'ordering': ['ac_month'],
            },
        ),
        migrations.CreateModel(
            name='ActualIndexes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ac_month', models.DateField(blank=True, null=True)),
                ('r_ufe', models.FloatField(blank=True, null=True)),
                ('r_tufe', models.FloatField(blank=True, null=True)),
                ('r_mineral', models.FloatField(blank=True, null=True)),
                ('r_main_metal', models.FloatField(blank=True, null=True)),
                ('r_val_metal', models.FloatField(blank=True, null=True)),
                ('r_petrol', models.FloatField(blank=True, null=True)),
                ('r_paper', models.FloatField(blank=True, null=True)),
                ('r_electricity', models.FloatField(blank=True, null=True)),
                ('r_computer', models.FloatField(blank=True, null=True)),
                ('r_usd_try', models.FloatField(blank=True, null=True)),
                ('r_eur_try', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('rep_month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constants.repmonth', verbose_name='Reporting Month')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_indexes_ac',
                'ordering': ['ac_month'],
                'unique_together': {('ac_month', 'rep_month')},
            },
        ),
        migrations.CreateModel(
            name='IndexIncRates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ac_month', models.DateField(blank=True, null=True)),
                ('kum_ufe', models.FloatField(blank=True, null=True)),
                ('kum_tufe', models.FloatField(blank=True, null=True)),
                ('kum_usd_try', models.FloatField(blank=True, null=True)),
                ('kum_eur_try', models.FloatField(blank=True, null=True)),
                ('usd_try', models.FloatField(blank=True, null=True)),
                ('eur_try', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('rep_month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constants.repmonth', verbose_name='Reporting Month')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_indexes_inc_rates',
                'ordering': ['ac_month'],
                'unique_together': {('ac_month', 'rep_month')},
            },
        ),
    ]
