# Generated by Django 5.0.7 on 2024-07-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actualindexes',
            unique_together={('ac_month',)},
        ),
        migrations.RemoveField(
            model_name='actualindexes',
            name='rep_month',
        ),
    ]
