# Generated by Django 5.0.7 on 2024-07-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0002_alter_actualindexes_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actualindexes',
            old_name='r_computer',
            new_name='b01_tufe',
        ),
        migrations.RenameField(
            model_name='actualindexes',
            old_name='r_electricity',
            new_name='b02_mineral',
        ),
        migrations.RenameField(
            model_name='actualindexes',
            old_name='r_main_metal',
            new_name='b03_main_metal',
        ),
        migrations.RenameField(
            model_name='actualindexes',
            old_name='r_mineral',
            new_name='b04_other_metal',
        ),
        migrations.RenameField(
            model_name='actualindexes',
            old_name='r_paper',
            new_name='b05_petrol',
        ),
        migrations.RenameField(
            model_name='actualindexes',
            old_name='r_petrol',
            new_name='b06_wood',
        ),
        migrations.RenameField(
            model_name='actualindexes',
            old_name='r_tufe',
            new_name='b07_electricity',
        ),
        migrations.RenameField(
            model_name='actualindexes',
            old_name='r_ufe',
            new_name='b08_computer',
        ),
        migrations.RenameField(
            model_name='actualindexes',
            old_name='r_val_metal',
            new_name='b09_ufe',
        ),
        migrations.AddField(
            model_name='actualindexes',
            name='b10_machinety',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
