# Generated by Django 5.0.7 on 2024-07-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0003_rename_r_computer_actualindexes_b01_tufe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actualindexes',
            old_name='b10_machinety',
            new_name='b10_machinery',
        ),
    ]
