# Generated by Django 5.0.7 on 2024-07-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0004_rename_b10_machinety_actualindexes_b10_machinery'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexincrates',
            name='art_eur_try',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexincrates',
            name='art_tufe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexincrates',
            name='art_ufe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexincrates',
            name='art_usd_try',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
