# Generated by Django 5.0.7 on 2024-07-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0005_indexincrates_art_eur_try_indexincrates_art_tufe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexincrates',
            name='eur_try',
        ),
        migrations.RemoveField(
            model_name='indexincrates',
            name='kum_eur_try',
        ),
        migrations.RemoveField(
            model_name='indexincrates',
            name='kum_tufe',
        ),
        migrations.RemoveField(
            model_name='indexincrates',
            name='kum_ufe',
        ),
        migrations.RemoveField(
            model_name='indexincrates',
            name='kum_usd_try',
        ),
        migrations.RemoveField(
            model_name='indexincrates',
            name='usd_try',
        ),
    ]
