# Generated by Django 3.2.25 on 2024-06-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_import_export', '0002_fileimportexportstatus_file_process_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fileimportexportstatus',
            table='file_import_export_status',
        ),
    ]
