# Generated by Django 3.2.25 on 2024-07-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_import_export', '0003_alter_fileimportexportstatus_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimportexportstatus',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fileimportexportstatus',
            name='file_type',
            field=models.CharField(max_length=255),
        ),
    ]
