# Generated by Django 5.0.7 on 2024-10-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0005_rename_updates_update_alter_update_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ['-year_no', 'month_no']},
        ),
    ]
