# Generated by Django 5.0.6 on 2024-06-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('error_type', models.CharField(blank=True, max_length=60, null=True)),
                ('log_detail', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'CriticalLogs',
                'db_table': 'critical_logs',
            },
        ),
    ]
