# Generated by Django 5.0.7 on 2024-07-18 14:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='L1Code',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('l1_code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('code_comb', models.CharField(blank=True, editable=False, max_length=255)),
            ],
            options={
                'db_table': 't_l1_code',
                'ordering': ['l1_code'],
            },
        ),
        migrations.CreateModel(
            name='L2Code',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('l2_code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('code_comb', models.CharField(blank=True, editable=False, max_length=255)),
            ],
            options={
                'db_table': 't_l2_code',
                'ordering': ['l2_code'],
            },
        ),
        migrations.CreateModel(
            name='L3Code',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('l3_code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('code_comb', models.CharField(blank=True, editable=False, max_length=255)),
            ],
            options={
                'db_table': 't_l3_code',
                'ordering': ['l3_code'],
            },
        ),
        migrations.CreateModel(
            name='L4Code',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('l4_code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('mtc_dgs_nkt', models.CharField(max_length=10)),
                ('nak_ote', models.IntegerField(blank=True, null=True)),
                ('l4_hkds', models.BooleanField(default=False)),
                ('l4_calc_method', models.CharField(max_length=100)),
                ('l4_bf_dg', models.FloatField()),
                ('l4_mk_ks', models.FloatField()),
                ('tax', models.BooleanField(default=False)),
                ('code_comb', models.CharField(blank=True, editable=False, max_length=255)),
            ],
            options={
                'db_table': 't_l4_code',
                'ordering': ['l4_code'],
            },
        ),
    ]
