# Generated by Django 5.0.7 on 2024-07-18 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constants', '0002_initial'),
        ('libraries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='l1code',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='l1code',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='l1code',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='l2code',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='l2code',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='l2code',
            name='l1_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libraries.l1code', verbose_name='L1 Code'),
        ),
        migrations.AddField(
            model_name='l2code',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='l3code',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='l3code',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='l3code',
            name='l2_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libraries.l2code', verbose_name='L2 Code'),
        ),
        migrations.AddField(
            model_name='l3code',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='l4code',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='l4code',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='l4code',
            name='l3_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libraries.l3code', verbose_name='L3 Code'),
        ),
        migrations.AddField(
            model_name='l4code',
            name='l4_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='libraries.l4code', verbose_name='L4 Ref'),
        ),
        migrations.AddField(
            model_name='l4code',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='constants.unit', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='l4code',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
