# Generated by Django 5.0.7 on 2024-07-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0003_alter_l4code_l4_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='l4code',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
