# Generated by Django 5.0.7 on 2024-07-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0004_alter_l4code_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='l4code',
            name='l4_bf_dg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='l4code',
            name='l4_calc_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='l4code',
            name='l4_mk_ks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
