# Generated by Django 5.0.7 on 2024-07-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0005_alter_l4code_l4_bf_dg_alter_l4code_l4_calc_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='l4code',
            name='l4_calc_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
