# Generated by Django 5.0.7 on 2024-07-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0006_alter_l4code_l4_calc_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='l4code',
            name='aygm_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
