# Generated by Django 5.0.7 on 2024-07-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0007_l4code_aygm_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='l4code',
            name='aygm_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='l4code',
            name='aymg_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
