# Generated by Django 5.0.7 on 2024-07-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0008_l4code_aygm_group_l4code_aymg_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='l4code',
            old_name='aymg_desc',
            new_name='aygm_desc',
        ),
        migrations.AddField(
            model_name='l4code',
            name='aygm_sub_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
