# Generated by Django 5.0.7 on 2024-07-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0009_rename_aymg_desc_l4code_aygm_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='l4code',
            name='aygm_sub_group',
        ),
    ]
