# Generated by Django 5.0.7 on 2024-07-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0011_activitytype_activitytypedetail_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='l4code',
            unique_together={('aygm_code', 'activity_type_detail', 'code_comb')},
        ),
    ]
