# Generated by Django 5.0.7 on 2024-07-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0013_alter_activitytype_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='l4code',
            name='l4_delivery_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='l4code',
            name='l4_handover_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='l4code',
            name='l4_order_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
