# Generated by Django 5.0.7 on 2024-07-24 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0014_l4code_l4_delivery_ratio_l4code_l4_handover_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='l4code',
            name='activity_type',
            field=models.ForeignKey(default='184ac044-d031-402c-bc0b-cbe2305eae14', on_delete=django.db.models.deletion.PROTECT, to='libraries.activitytype', verbose_name='Income Activity Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='l4code',
            name='activity_detail',
            field=models.ForeignKey(default='5fff774f-b365-4db4-85fa-0cad7c959bae', on_delete=django.db.models.deletion.PROTECT, to='libraries.activitytypedetail', verbose_name='Income Activity Type Detail'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='l4code',
            unique_together={('aygm_code', 'activity_type', 'activity_detail', 'code_comb')},
        ),


        migrations.RemoveField(
            model_name='l4code',
            name='activity_type_detail',
        ),
    ]
