# Generated by Django 5.0.7 on 2024-07-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0015_remove_activitytypedetail_income_activity_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitytypedetail',
            name='income_activity_type',
        ),
    ]
