# Generated by Django 5.0.7 on 2024-07-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0018_r1code_r2code_r3code_r4code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='l1code',
            unique_together={('code_comb',)},
        ),
        migrations.AlterUniqueTogether(
            name='l2code',
            unique_together={('code_comb',)},
        ),
        migrations.AlterUniqueTogether(
            name='l3code',
            unique_together={('code_comb',)},
        ),
        migrations.AlterUniqueTogether(
            name='r1code',
            unique_together={('code_comb',)},
        ),
        migrations.AlterUniqueTogether(
            name='r2code',
            unique_together={('code_comb',)},
        ),
        migrations.AlterUniqueTogether(
            name='r3code',
            unique_together={('code_comb',)},
        ),
    ]
