# Generated by Django 5.0.7 on 2024-07-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0019_alter_l1code_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r1code',
            name='r1_code',
            field=models.CharField(max_length=5),
        ),
    ]
