# Generated by Django 5.0.7 on 2024-07-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0020_alter_r1code_r1_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r2code',
            name='r2_code',
            field=models.CharField(max_length=4),
        ),
    ]
