# Generated by Django 5.0.7 on 2024-07-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0021_alter_r2code_r2_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r4code',
            name='currency',
            field=models.CharField(blank=True, choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('TRY', 'Turkish Lira')], max_length=3, null=True),
        ),
    ]
