# Generated by Django 5.0.7 on 2024-07-27 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0023_alter_r4code_fin_type_alter_r4code_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r4code',
            name='r3_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraries.r3code', verbose_name='R3 Code'),
        ),
    ]
