# Generated by Django 5.0.7 on 2024-07-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0025_remove_r4code_currency_remove_r4code_customs_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='R4Price',
        ),
    ]
