# Generated by Django 5.0.7 on 2024-07-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0026_delete_r4price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='r4code',
            options={'ordering': ['code_comb']},
        ),
    ]
