# Generated by Django 5.0.7 on 2024-07-29 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0027_alter_r4code_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r3code',
            name='r2_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraries.r2code', verbose_name='R2 Code'),
        ),
    ]
