# Generated by Django 5.0.7 on 2024-07-29 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0028_alter_r3code_r2_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='l4code',
            options={'ordering': ['code_comb']},
        ),
    ]
