# Generated by Django 5.0.7 on 2024-08-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0029_alter_l4code_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='l1code',
            name='code_comb',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='l2code',
            name='code_comb',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='l3code',
            name='code_comb',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='l4code',
            name='code_comb',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='r1code',
            name='code_comb',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='r2code',
            name='code_comb',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='r3code',
            name='code_comb',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='r4code',
            name='code_comb',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
