# Generated by Django 5.0.7 on 2024-08-07 05:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0032_t1code_y1code_t2code_y2code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='y2code',
            name='y1_code',
        ),
        migrations.AlterUniqueTogether(
            name='y2code',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='y2code',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='y2code',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='y2code',
            name='updated_by',
        ),
        migrations.CreateModel(
            name='M1Code',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('m1_code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('code_comb', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_m1_code',
                'ordering': ['m1_code'],
                'unique_together': {('code_comb',)},
            },
        ),
        migrations.CreateModel(
            name='M2Code',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('m2_code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('code_comb', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('m1_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libraries.m1code', verbose_name='Y1 Code')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_m2_code',
                'ordering': ['m2_code'],
                'unique_together': {('code_comb',)},
            },
        ),
        migrations.DeleteModel(
            name='Y1Code',
        ),
        migrations.DeleteModel(
            name='Y2Code',
        ),
    ]
