# Generated by Django 5.0.7 on 2024-08-10 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0036_r4code_m2_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='r4code',
            name='t1_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='libraries.t1code', verbose_name='T1 Code'),
        ),
    ]
