# Generated by Django 5.0.7 on 2024-08-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0037_r4code_t1_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='r4code',
            name='m2_code',
        ),
        migrations.RemoveField(
            model_name='r4code',
            name='t1_code',
        ),
    ]
