# Generated by Django 5.0.7 on 2024-08-11 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0033_alter_t1code_unique_together_delete_t2code_and_more'),
        ('libraries', '0038_remove_r4code_m2_code_remove_r4code_t1_code'),
    ]

    operations = [
    ]
