# Generated by Django 5.0.7 on 2024-08-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0039_merge_20240811_1024'),
    ]

    operations = [
    ]
