# Generated by Django 5.0.7 on 2024-08-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0040_auto_20240811_1026'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='t1code',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='t1code',
            name='code_comb',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='t1code',
            unique_together={('code_comb',)},
        ),
    ]
