# Generated by Django 5.0.7 on 2024-08-11 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0041_alter_t1code_unique_together_t1code_code_comb_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='t1code',
            unique_together={('t1_code',)},
        ),
    ]
