# Generated by Django 5.0.7 on 2024-08-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0043_alter_t1code_unique_together_t1code_price_adjustment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='t1code',
            unique_together=set(),
        ),
    ]
