# Generated by Django 5.0.7 on 2024-08-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0044_alter_t1code_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='t1code',
            unique_together={('t1_code', 'price_adjustment')},
        ),
    ]
