# Generated by Django 5.0.7 on 2024-08-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0045_alter_t1code_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='t1code',
            name='contract_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t1code',
            name='price_adjustment',
            field=models.CharField(blank=True, choices=[('FFK AK', 'FFK AK'), ('YKT AK', 'YKT AK'), ('BKM AK', 'BKM AK'), ('EUR AK', 'EUR AK'), ('USD AK', 'USD AK'), ('DGS.01', 'DGS.01'), ('DGS.02', 'DGS.02'), ('-', '-')], max_length=100, null=True),
        ),
    ]
