# Generated by Django 5.0.7 on 2024-08-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0046_t1code_contract_no_alter_t1code_price_adjustment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='r1code',
            options={'ordering': ['code_comb']},
        ),
        migrations.AlterModelOptions(
            name='r2code',
            options={'ordering': ['code_comb']},
        ),
        migrations.AlterModelOptions(
            name='r3code',
            options={'ordering': ['code_comb']},
        ),
    ]
