# Generated by Django 5.0.7 on 2024-09-05 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0049_alter_t1code_price_adjustment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t1code',
            options={'ordering': ['t1_code', 'price_adjustment']},
        ),
    ]
