# Generated by Django 5.0.7 on 2024-10-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0050_alter_t1code_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='r4code',
            name='fin_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='r4code',
            name='fin_model_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
