# Generated by Django 5.0.7 on 2024-10-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0051_r4code_fin_model_r4code_fin_model_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r4code',
            name='fin_model',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
