# Generated by Django 5.0.7 on 2024-10-15 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0052_alter_r4code_fin_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='r4code',
            name='fin_model',
        ),
        migrations.RemoveField(
            model_name='r4code',
            name='fin_model_ratio',
        ),
    ]
