# Generated by Django 5.0.7 on 2024-07-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r4price',
            name='content_constant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='r4price',
            name='origin',
            field=models.CharField(blank=True, choices=[('TR', 'TR'), ('OECD', 'OECD'), ('OEKB', 'OEKB'), ('SACE', 'SACE'), ('UKEF', 'UKEF'), ('KUKE', 'KUKE'), ('-', '-')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='r4price',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='r4price',
            name='price_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
