# Generated by Django 5.0.7 on 2024-07-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_r4price_content_constant_alter_r4price_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='r4price',
            name='depreciation_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='r4price',
            name='depreciation_type',
            field=models.CharField(blank=True, choices=[('MAKİNE', 'MAKİNE'), ('SABİT TESİS', 'SABİT TESİS'), ('ARAÇ', 'ARAÇ'), ('DİĞER EKİPMANLAR', 'DİĞER EKİPMANLAR'), ('-', '-')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='r4price',
            name='energy_type',
            field=models.CharField(blank=True, choices=[('ELEKTRİK', 'ELEKTRİK'), ('DOĞALGAZ', 'DOĞALGAZ'), ('BUHAR', 'BUHAR'), ('MAZOT', 'MAZOT'), ('-', '-')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='r4price',
            name='price_adjustment_type',
            field=models.CharField(blank=True, choices=[('FFK AK', 'FFK AK'), ('YKT AK', 'YKT AK'), ('BKM AK', 'BKM AK'), ('EUR AK', 'EUR AK'), ('USD AK', 'USD AK'), ('-', '-')], max_length=100, null=True),
        ),
    ]
