# Generated by Django 5.0.7 on 2024-07-29 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_expenseanalysis'),
        ('libraries', '0028_alter_r3code_r2_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenseanalysis',
            old_name='output_per_unit',
            new_name='consumption_per_unit',
        ),
        migrations.AlterUniqueTogether(
            name='expenseanalysis',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='expenseanalysis',
            name='l4_code',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='l4_code_analysis', to='libraries.l4code', verbose_name='L4 Code Analysis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseanalysis',
            name='r4_code_self',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='self_r4_prices_analysis', to='expense.expenseanalysis', verbose_name='R4 Code Self Analysis'),
        ),
        migrations.AddField(
            model_name='expenseanalysis',
            name='work_ratio_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expenseanalysis',
            name='r4_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='r4_prices_analysis', to='libraries.r4code', verbose_name='R4 Code Analysis'),
        ),
    ]
