# Generated by Django 5.0.7 on 2024-07-29 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_rename_output_per_unit_expenseanalysis_consumption_per_unit_and_more'),
        ('libraries', '0028_alter_r3code_r2_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenseanalysis',
            old_name='consumption_per_unit',
            new_name='consumption_per_unit_time',
        ),
        migrations.AddField(
            model_name='expenseanalysis',
            name='consumption_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expenseanalysis',
            name='output_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expenseanalysis',
            name='output_per_unit_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenseanalysis',
            name='r4_code_consumption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='r4_prices_consumption', to='libraries.r4code', verbose_name='R4 Code Consumption'),
        ),
    ]
