# Generated by Django 5.0.7 on 2024-07-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_rename_consumption_per_unit_expenseanalysis_consumption_per_unit_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseanalysis',
            name='r4_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
