# Generated by Django 5.0.7 on 2024-07-29 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0009_alter_r4price_r4_code'),
        ('libraries', '0029_alter_l4code_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r4price',
            name='operator_r4_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_r4_prices', to='libraries.r4code', verbose_name='Operator R4 Code'),
        ),
    ]
