# Generated by Django 5.0.7 on 2024-07-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0010_alter_r4price_operator_r4_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseanalysis',
            name='r4_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
