# Generated by Django 5.0.7 on 2024-07-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0011_expenseanalysis_r4_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseanalysis',
            name='r4_code_consumption',
        ),
        migrations.RemoveField(
            model_name='expenseanalysis',
            name='r4_type',
        ),
    ]
