# Generated by Django 5.0.7 on 2024-07-30 15:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0005_rename_updates_update_alter_update_table'),
        ('expense', '0014_expensemachinerydistribution_machine_r4_code'),
        ('libraries', '0029_alter_l4code_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpenseMachineryDistribution',
            new_name='ExpenseMachineryOperatorDistribution',
        ),
        migrations.AlterModelTable(
            name='expensemachineryoperatordistribution',
            table='t_exp_mach_oper_dist',
        ),
    ]
