# Generated by Django 5.0.7 on 2024-08-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0017_r4price_deprciation_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='r4price',
            old_name='deprciation_quantity',
            new_name='depreciation_quantity',
        ),
    ]
