# Generated by Django 5.0.7 on 2024-08-07 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0005_rename_updates_update_alter_update_table'),
        ('expense', '0018_rename_deprciation_quantity_r4price_depreciation_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='r4price',
            name='capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='r4price',
            name='capacity_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capacity_unit_r4_prices', to='constants.unit', verbose_name='Capacity Unit name'),
        ),
        migrations.AddField(
            model_name='r4price',
            name='energy_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='energy_unit_r4_prices', to='constants.unit', verbose_name='Energy Unit name'),
        ),
        migrations.AlterField(
            model_name='r4price',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_r4_prices', to='constants.unit', verbose_name='Unit'),
        ),
    ]
