# Generated by Django 5.0.7 on 2024-08-07 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0019_r4price_capacity_r4price_capacity_unit_and_more'),
        ('libraries', '0035_r4code_machine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseanalysis',
            name='m2_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='m2_code_analysis', to='libraries.m2code', verbose_name='M2 Code'),
        ),
        migrations.AddField(
            model_name='expenseanalysis',
            name='t1_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='t1_code_analysis', to='libraries.t1code', verbose_name='T1 Code'),
        ),
        migrations.AddField(
            model_name='expensemachineryoperatordistribution',
            name='m2_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='m2_code_expense_machiner', to='libraries.m2code', verbose_name='M2 Code'),
        ),
        migrations.AddField(
            model_name='expensemachineryoperatordistribution',
            name='t1_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='t1_code_expense_machiner', to='libraries.t1code', verbose_name='T1 Code'),
        ),
        migrations.AddField(
            model_name='expensequantity',
            name='m2_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='m2_code_expense_qty', to='libraries.m2code', verbose_name='M2 Code'),
        ),
        migrations.AddField(
            model_name='expensequantity',
            name='t1_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='t1_code_expense_qty', to='libraries.t1code', verbose_name='T1 Code'),
        ),
        migrations.AlterField(
            model_name='expensemachineryoperatordistribution',
            name='machine_qty',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='MachineryList',
        ),
    ]
