# Generated by Django 5.0.7 on 2024-08-08 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0021_machinerylist'),
        ('libraries', '0035_r4code_machine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseanalysis',
            name='r3_code_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='r3_code_machine', to='libraries.r3code', verbose_name='R3 Code Machine'),
        ),
    ]
