# Generated by Django 5.0.7 on 2024-08-10 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0022_expenseanalysis_r3_code_machine'),
        ('libraries', '0038_remove_r4code_m2_code_remove_r4code_t1_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='r4price',
            name='m2_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='libraries.m2code', verbose_name='M2 Code'),
        ),
        migrations.AddField(
            model_name='r4price',
            name='t1_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='libraries.t1code', verbose_name='T1 Code'),
        ),
    ]
