# Generated by Django 5.0.7 on 2024-08-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0025_alter_r4price_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r4price',
            name='price_adjustment_type',
            field=models.CharField(blank=True, choices=[('FFK AK', 'FFK AK'), ('YKT AK', 'YKT AK'), ('BKM AK', 'BKM AK'), ('EUR AK', 'EUR AK'), ('USD AK', 'USD AK'), ('-', '-')], max_length=100, null=True),
        ),
    ]
