# Generated by Django 5.0.7 on 2024-08-13 06:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0005_rename_updates_update_alter_update_table'),
        ('expense', '0026_alter_r4price_price_adjustment_type'),
        ('libraries', '0047_alter_r1code_options_alter_r2code_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('exp_month', models.DateField()),
                ('exp_qty', models.FloatField(default=0)),
                ('exp', models.FloatField(default=0)),
                ('currency', models.CharField(blank=True, choices=[('TRY', 'TRY'), ('EUR', 'EUR'), ('USD', 'USD')], max_length=3, null=True)),
                ('bool_depriciation', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('exp_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exp_unit', to='constants.unit', verbose_name='Expense Unit')),
                ('l4_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libraries.l4code', verbose_name='Expense_l4_code')),
                ('m2_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='m2_code_expense', to='libraries.m2code', verbose_name='M2 Code')),
                ('r3_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='libraries.r3code', verbose_name='Expense_r3_code')),
                ('r4_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libraries.r4code', verbose_name='Expense_r4_code')),
                ('rep_month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constants.repmonth', verbose_name='Expense_rep_month')),
                ('t1_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='t1_code_expense', to='libraries.t1code', verbose_name='T1 Code')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_exp',
                'ordering': ['exp_month', 'l4_code__code_comb', 'm2_code__code_comb', 't1_code__code_comb'],
            },
        ),
        migrations.DeleteModel(
            name='MachineryList',
        ),
    ]
