# Generated by Django 5.0.7 on 2024-08-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0027_expense_delete_machinerylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseanalysis',
            name='r3_currency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR'), ('USD', 'USD'), ('TRY', 'TRY')], max_length=3, null=True),
        ),
    ]
