# Generated by Django 5.0.7 on 2024-08-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0005_rename_updates_update_alter_update_table'),
        ('expense', '0028_expenseanalysis_r3_currency'),
        ('libraries', '0047_alter_r1code_options_alter_r2code_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('rep_month', 'r3_code', 'r4_code', 'm2_code', 't1_code', 'exp_month', 'currency')},
        ),
    ]
