# Generated by Django 5.0.7 on 2024-08-14 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0029_alter_expense_unique_together'),
        ('libraries', '0047_alter_r1code_options_alter_r2code_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['l4_code__code_comb', 'm2_code__code_comb', 't1_code__code_comb', 'exp_month']},
        ),
        migrations.AlterField(
            model_name='expense',
            name='m2_code',
            field=models.ForeignKey(default='9c7ce490-3ee4-4e30-bcec-f0e2ad1f83f5', on_delete=django.db.models.deletion.PROTECT, related_name='m2_code_expense', to='libraries.m2code', verbose_name='M2 Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='r4_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='libraries.r4code', verbose_name='Expense_r4_code'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='t1_code',
            field=models.ForeignKey(default='a1445ae2-479a-4630-bc1a-a68ac36c85f2', on_delete=django.db.models.deletion.PROTECT, related_name='t1_code_expense', to='libraries.t1code', verbose_name='T1 Code'),
            preserve_default=False,
        ),
    ]
