# Generated by Django 5.0.7 on 2024-08-14 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0030_alter_expense_options_alter_expense_m2_code_and_more'),
        ('libraries', '0047_alter_r1code_options_alter_r2code_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensequantity',
            name='m2_code',
            field=models.ForeignKey(default='9c7ce490-3ee4-4e30-bcec-f0e2ad1f83f5', on_delete=django.db.models.deletion.PROTECT, related_name='m2_code_expense_qty', to='libraries.m2code', verbose_name='M2 Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expensequantity',
            name='t1_code',
            field=models.ForeignKey(default='646024b3-323c-4ccb-9829-11902395c0ad', on_delete=django.db.models.deletion.PROTECT, related_name='t1_code_expense_qty', to='libraries.t1code', verbose_name='T1 Code'),
            preserve_default=False,
        ),
    ]
