# Generated by Django 5.0.7 on 2024-08-20 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0031_alter_expensequantity_m2_code_and_more'),
        ('libraries', '0048_alter_t1code_price_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(blank=True, choices=[('TRY', 'TRY'), ('EUR', 'EUR'), ('USD', 'USD')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='r3_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='libraries.r3code', verbose_name='Expense_r3_code'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='r4_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='libraries.r4code', verbose_name='Expense_r4_code'),
        ),
    ]
