# Generated by Django 5.0.7 on 2024-08-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0032_alter_expense_currency_alter_expense_r3_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemachineryoperatordistribution',
            name='r4_usage_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
