# Generated by Django 5.0.7 on 2024-08-23 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0005_rename_updates_update_alter_update_table'),
        ('expense', '0033_expensemachineryoperatordistribution_r4_usage_desc'),
        ('libraries', '0048_alter_t1code_price_adjustment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expenseanalysis',
            unique_together={('rep_month', 'l4_code', 'r4_code', 'r4_desc', 'r3_code_machine', 'm2_code', 't1_code')},
        ),
    ]
