# Generated by Django 5.0.7 on 2024-08-27 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0034_alter_expenseanalysis_unique_together'),
        ('libraries', '0048_alter_t1code_price_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseanalysis',
            name='m2_code',
            field=models.ForeignKey(default='4b154f73-aa31-4e86-a590-c0f5bd241d6f', on_delete=django.db.models.deletion.PROTECT, related_name='m2_code_analysis', to='libraries.m2code', verbose_name='M2 Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenseanalysis',
            name='t1_code',
            field=models.ForeignKey(default='8d2bc0e6-2943-4855-9305-c778cd695f09', on_delete=django.db.models.deletion.PROTECT, related_name='t1_code_analysis', to='libraries.t1code', verbose_name='T1 Code'),
            preserve_default=False,
        ),
    ]
