# Generated by Django 5.0.7 on 2024-09-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0005_rename_updates_update_alter_update_table'),
        ('expense', '0035_alter_expenseanalysis_m2_code_and_more'),
        ('libraries', '0049_alter_t1code_price_adjustment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expensequantity',
            unique_together={('rep_month', 'l4_code', 'm2_code', 't1_code', 'exp_month')},
        ),
    ]
