# Generated by Django 5.0.7 on 2024-09-10 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0005_rename_updates_update_alter_update_table'),
        ('expense', '0039_alter_expenseanalysis_unique_together_and_more'),
        ('libraries', '0050_alter_t1code_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expenseanalysis',
            name='unique_expense_analysis_no_r3_code_machine',
        ),
        migrations.RemoveConstraint(
            model_name='expenseanalysis',
            name='unique_expense_analysis_with_r3_code_machine',
        ),
        migrations.AddField(
            model_name='expenseanalysis',
            name='r4_operator_machine_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='r4_operator_machine_code', to='libraries.r4code', verbose_name='R4 Operator Machine Code'),
        ),
        migrations.AddConstraint(
            model_name='expenseanalysis',
            constraint=models.UniqueConstraint(fields=('rep_month', 'l4_code', 'r4_code', 'r4_desc', 'm2_code', 't1_code', 'r4_operator_machine_code'), name='unique_expense_analysis_no_r3_code_machine'),
        ),
        migrations.AddConstraint(
            model_name='expenseanalysis',
            constraint=models.UniqueConstraint(condition=models.Q(('r3_code_machine__isnull', False)), fields=('rep_month', 'l4_code', 'r4_code', 'r4_desc', 'r3_code_machine', 'm2_code', 't1_code', 'r4_operator_machine_code'), name='unique_expense_analysis_with_r3_code_machine'),
        ),
    ]
