# Generated by Django 5.0.7 on 2024-09-11 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0005_rename_updates_update_alter_update_table'),
        ('expense', '0040_remove_expenseanalysis_unique_expense_analysis_no_r3_code_machine_and_more'),
        ('libraries', '0050_alter_t1code_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expenseanalysis',
            name='unique_expense_analysis_no_r3_code_machine',
        ),
        migrations.RemoveConstraint(
            model_name='expenseanalysis',
            name='unique_expense_analysis_with_r3_code_machine',
        ),
        migrations.RemoveField(
            model_name='expenseanalysis',
            name='r4_operator_machine_code',
        ),
        migrations.AddConstraint(
            model_name='expenseanalysis',
            constraint=models.UniqueConstraint(fields=('rep_month', 'l4_code', 'r4_code', 'r4_desc', 'm2_code', 't1_code'), name='unique_expense_analysis_no_r3_code_machine'),
        ),
        migrations.AddConstraint(
            model_name='expenseanalysis',
            constraint=models.UniqueConstraint(condition=models.Q(('r3_code_machine__isnull', False)), fields=('rep_month', 'l4_code', 'r4_code', 'r4_desc', 'r3_code_machine', 'm2_code', 't1_code'), name='unique_expense_analysis_with_r3_code_machine'),
        ),
    ]
