# Generated by Django 5.0.7 on 2024-10-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0041_remove_expenseanalysis_unique_expense_analysis_no_r3_code_machine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensequantity',
            name='qty_type',
            field=models.BooleanField(default=True),
        ),
    ]
