# Generated by Django 5.0.7 on 2024-10-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0042_expensequantity_qty_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='r4price',
            name='fin_model',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='r4price',
            name='fin_model_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
