# Generated by Django 5.0.7 on 2024-10-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0044_alter_r4price_fin_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='r4price',
            options={'ordering': ['price_date'], 'verbose_name_plural': 'R4 Prices Test'},
        ),
    ]
