# Generated by Django 5.0.7 on 2024-10-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0045_alter_r4price_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r4price',
            name='depreciation_type',
            field=models.CharField(blank=True, choices=[('MAKİNE', 'MAKİNE'), ('SABİT TESİS', 'SABİT TESİS'), ('ARAÇ', 'ARAÇ'), ('DİĞER EKİPMANLAR', 'DİĞER EKİPMANLAR'), ('ZEMİN', 'ZEMİN'), ('-', '-')], max_length=100, null=True),
        ),
    ]
