# Generated by Django 5.0.7 on 2024-07-23 08:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0003_month'),
        ('income', '0001_initial'),
        ('libraries', '0010_remove_l4code_aygm_sub_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeQuantity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('inc_month', models.DateField()),
                ('inc_qty', models.FloatField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('income_activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='income.incomeactivitytype', verbose_name='Income Activity Type')),
                ('income_activity_type_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='income.incomeactivitytypedetail', verbose_name='Income Activity Type Detail')),
                ('l4_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libraries.l4code', verbose_name='income_l4_code')),
                ('rep_month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constants.repmonth', verbose_name='income_rep_month')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_inc_qty',
                'ordering': ['l4_code'],
            },
        ),
    ]
