# Generated by Django 5.0.7 on 2024-07-24 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_remove_incomequantity_income_activity_type_and_more'),
        ('libraries', '0017_activitytypedetailincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomequantity',
            name='activity_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='libraries.activitytypedetailincome', verbose_name='Income Type Detail'),
        ),
    ]
