# Generated by Django 5.0.7 on 2024-10-11 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0006_alter_incomeindexes_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incomeindexes',
            unique_together={('inc_month',)},
        ),
    ]
