# Generated by Django 5.0.7 on 2024-10-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0007_alter_incomeindexes_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incomeindexes',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='incomeindexes',
            name='ppr_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='incomeindexes',
            unique_together={('inc_month', 'ppr_no')},
        ),
    ]
