# Generated by Django 5.0.7 on 2024-10-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0005_rename_updates_update_alter_update_table'),
        ('income', '0009_incomequantitybyppr'),
        ('libraries', '0050_alter_t1code_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incomequantitybyppr',
            unique_together={('rep_month', 'l4_code', 'inc_month', 'ppr_no', 'activity_detail')},
        ),
    ]
