# Generated by Django 5.0.7 on 2024-10-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0010_alter_incomequantitybyppr_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeindexes',
            name='inc_inc_w_otv',
            field=models.FloatField(default=0),
        ),
    ]
